// Code generated by "stringer -type=EventType"; DO NOT EDIT.

package gooldb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Connected-0]
	_ = x[ConnectError-1]
	_ = x[Reconnected-2]
	_ = x[ReconnectError-3]
	_ = x[Disconnected-4]
	_ = x[DisconnectError-5]
	_ = x[DriverLoadError-6]
	_ = x[DBOpened-7]
	_ = x[DBOpenError-8]
	_ = x[DatabaseListFetched-9]
	_ = x[DatabaseListFetchError-10]
	_ = x[DBTableListFetched-11]
	_ = x[DBTableListFetchError-12]
	_ = x[TableSelected-13]
	_ = x[TableSelectError-14]
	_ = x[TableFetched-15]
	_ = x[TableFetchError-16]
	_ = x[TableCountFetched-17]
	_ = x[QueryExecuted-18]
	_ = x[QueryExecuteError-19]
}

const _EventType_name = "ConnectedConnectErrorReconnectedReconnectErrorDisconnectedDisconnectErrorDriverLoadErrorDBOpenedDBOpenErrorDatabaseListFetchedDatabaseListFetchErrorDBTableListFetchedDBTableListFetchErrorTableSelectedTableSelectErrorTableFetchedTableFetchErrorTableCountFetchedQueryExecutedQueryExecuteError"

var _EventType_index = [...]uint16{0, 9, 21, 32, 46, 58, 73, 88, 96, 107, 126, 148, 166, 187, 200, 216, 228, 243, 260, 273, 290}

func (i EventType) String() string {
	if i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
